Tai/main menu options
enochtsang/TerminalFighter pull request #106
Opened 2017-11-29 04:12 UTC by ctlai95

2017-11-29 04:34 UTC, ExtraGravity requested changes

2017-11-29 04:34 UTC, enochtsang commented on src/TerminalFighter/TextArea/TextArea.h
> +#define WHITE {255, 255, 255}
Use anonymous name spaces instead of defines.

```
namespace {
    int FOO 4;
}
```

2017-11-29 04:34 UTC, enochtsang commented on src/TerminalFighter/MainMenu/MainMenu.cpp
> +    current_selection_ = (2 + (current_selection_ + 1) % 2) % 2;
This math isn't the easiest to reason through. Can we do this more readable with conditionals?

2017-11-29 04:34 UTC, enochtsang commented on src/TerminalFighter/MainMenu/MainMenu.cpp
> +        0.1 * height,
Comments explaining the reasoning for these numbers would be helpful. It's not immediately clear what they do.

2017-11-29 04:34 UTC, enochtsang commented on src/TerminalFighter/MainMenu/MainMenu.h
> +const int QUIT = 1;
Put these in an anonymous namespace.

2017-12-01 02:06 UTC, bseto commented
I like it. However, I feel like you can make this more generic. We will add more options in the future. I know at the moment, our config files are used for user configurations, but I think we will also one day have our own developer configs where it's like "encrypted". (So maybe have all the values of title, start, and quit in a config). 

Maybe for now, we can keep it like this as @enochtsang may argue that this is ok for the main menu.

But I feel in the future, we should have a pretty generic menu object where you can give it an array of menu options, and it'll just dynamically build the the menu. 

The options could include (as an example):
- Menu options (Start, Settings, Quit, etc..)
- Menu Border (toggle)
- Menu transparency value
- Leftmost X,Y position
- Scrollable
- Sound effects etc

The only thing that I don't like is the `move_up_selection()` and the move down one. 
Using two modulus operators there make the logic hard to read. I know it's supposed to wrap and stuff, and I can assume. But I don't really want to check the logic, and I won't want to check it again in the future. I recommend simple if statements.

2017-12-01 02:07 UTC, bseto approved these changes

2017-12-01 02:56 UTC, ctlai95 commented
I really like those ideas, let's discuss it more in the future. Merging this to the main branch for now.

2017-12-01 02:56 UTC, merged