Added CMake
enochtsang/TerminalFighter pull request #77
Opened 2017-05-26 09:52 UTC by bseto

To run this.

1. Go to top level directory of TerminalFighter
2. create a new directory called 'build' `mkdir build`
3. run `cmake ..`
4. run `make` (you can use `make -j8` or whatever if you want parallel compiling - yes, it works)

In hindsight, I think travis will fail.

2017-05-26 19:53 UTC, enochtsang commented
Should fix the travis build.

2017-05-30 08:31 UTC, ExtraGravity requested changes
- FindSDL2_ttf.cmake was taken from somewhere right?

- For travis, using the following wget, `https://l.messenger.com/l.php?u=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fastyle%2Ffiles%2Fastyle%2Fastyle%25203.0%2Fastyle_3.0_linux.tar.gz%2Fdownload&h=ATMZImYXU7vmymhRfm0DIngfMBFkkyoei50lUJuQPU8HjwDV7g2yB3jauK7Jt2J7lp0oFImOy-n3Ozhxy9o77q8ayXz1r-eetuZLojLiybdCg4zgVGDp8n2XwJb4iHiBwAatRWGcONo`

- Lastly, I think the Gamestates should stay in it's own DIR, it'll need it's own CMakeLists.txt, and it's something we should probably learn to do now. Or we're not going to use multiple DIRS in the future just because we don't want to go through the hassle of learning how to set it up.

- README should be updated with build steps

2017-06-16 07:21 UTC, ExtraGravity requested changes
Still need to test it on my machine.

2017-06-16 07:21 UTC, enochtsang commented on FindSDL2_ttf.cmake
> +endif ()
This whole file you took from somewhere else right?

2017-06-16 07:21 UTC, enochtsang commented on README.adoc
> +`./build-all.sh`
You mean make-all? Well I think build-all is a better name now that we dont' use makefile directly. So renaming the mak-all script would be better.

2017-06-16 07:21 UTC, enochtsang commented on src/gamestates/CMakeLists.txt
> +target_link_libraries(TestState GameObjectMediator Universe CollisionDetector BasicEnemy GraphicsHandler MainCharacter MissileLauncher Events Delay Keyboard)
Can we multiline this?

2017-06-16 07:21 UTC, enochtsang commented on src/gamestates/I_Gamestate.h
> +/* #include <SDL.h> */
Delete?

2017-06-16 07:21 UTC, enochtsang commented on src/gamestates/TestState.cpp
> +#include "src/GameObjectMediator.h"
All this src/ is pretty ugly, can we get rid of it?

2017-06-16 07:21 UTC, enochtsang commented on src/gamestates/TestState.h
> +#include <src/gamestates/I_Gamestate.h>
Use quotes instead of brackets.

2017-06-16 07:21 UTC, enochtsang commented on test/TestAll.cpp
> +#include "MissileLauncherTest.cpp"
You shouldn't ever need to include cpp files, that's a recipe for circular dependencies. Also, gtest is supposed ot have auotomatic test discovery that doesn't need this.

2017-06-16 11:24 UTC, bseto commented on FindSDL2_ttf.cmake
> +endif ()
Yep

2017-06-16 11:25 UTC, bseto commented on src/gamestates/CMakeLists.txt
> +target_link_libraries(TestState GameObjectMediator Universe CollisionDetector BasicEnemy GraphicsHandler MainCharacter MissileLauncher Events Delay Keyboard)
Good idea

2017-06-16 11:26 UTC, bseto commented on README.adoc
> +`./build-all.sh`
Ok, I can do that

2017-06-16 11:27 UTC, bseto commented on src/gamestates/TestState.cpp
> +#include "src/GameObjectMediator.h"
Not sure :/, tried to look into it b4 but things I tried didn't work. Tried a big combination of things with the cmake and the file includes. Il give it one more shot though

2017-06-16 16:12 UTC, enochtsang commented on src/gamestates/TestState.cpp
> +#include "src/GameObjectMediator.h"
We can run the build within the src directory too, and the make all script will just cd into the src before running it's current stuff.

2017-06-17 03:00 UTC, bseto commented on test/TestAll.cpp
> +#include "MissileLauncherTest.cpp"
W/o the includes, i get:
[==========] Running 0 tests from 0 test cases.
[==========] 0 tests from 0 test cases ran. (0 ms total)
[  PASSED  ] 0 tests.

Not sure why, but when we used a normal makefile, it'd discover the tests, but w/ CMake, it seems like i need the includes for these. 

Example where they do it: https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/

2017-06-17 03:19 UTC, bseto commented on src/gamestates/TestState.cpp
> +#include "src/GameObjectMediator.h"
? sorry i don't follow.

2017-06-22 20:22 UTC, enochtsang commented on test/TestAll.cpp
> +#include "MissileLauncherTest.cpp"
I think there's a call in CMakeLists to add tests. https://cmake.org/cmake/help/v3.0/module/FindGTest.html I would try that, including cpp files can make some really funky errors :/

2017-06-26 16:14 UTC, merged